"""Initial migration for congestion and logs tables

Revision ID: 74c0fdc8a98f
Revises: 
Create Date: 2025-04-11 15:54:56.404651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c0fdc8a98f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('congestion', schema=None) as batch_op:
        batch_op.alter_column('station',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('crowd_level',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint('uq_station_time', ['station', 'start_time', 'end_time'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('log',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('log',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('congestion', schema=None) as batch_op:
        batch_op.drop_constraint('uq_station_time', type_='unique')
        batch_op.alter_column('crowd_level',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('station',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
